Days of week option and windows setup
maraid/parkanizerer pull request #1
Opened 2023-06-14 11:53 UTC by kArmadi110

2023-06-17 06:56 UTC, maraid requested changes
Thanks for the PR, it's greatly appreciated. I added some comments

2023-06-17 06:56 UTC, maraid commented on parkanizerer.cmd
> +python main.py
Is this needed? With the  hasbang #!/usr/bin/env python3 the script should be runnable directly, but I'm not sure if it is accepted as startup script.

2023-06-17 06:56 UTC, maraid commented on main.py
> +def fetch_desk_id(desk_name, zone_id, days_to_take):
single day_to_take
```suggestion
def fetch_desk_id(desk_name, zone_id, day_to_take):
```

2023-06-17 06:56 UTC, maraid commented on main.py
> +
This calculation is a bit all around. Can I suggest a denser form?

```suggestion
        today = datetime.today()
        days_left = (dow - today.weekday()) % 7
        next_day = today + datetime.timedelta(days=days_left)
```

2023-06-17 06:56 UTC, maraid commented on main.py
> +    if not config["days_of_week"]:
Please use config.get() for backwards compatibility
```suggestion
    if not config.get("days_of_week", []):
```

2023-06-17 06:56 UTC, maraid commented on main.py
> +
Please add else branch here for clarity

2023-06-19 06:23 UTC, kArmadi110 commented on parkanizerer.cmd
> +python main.py
Don't quote me on that but afaik by default shebang isn't supported on windows. The other option would be to handle this by file extension association but for most developers the .py extension is associated with an IDE and not with the interpreter.
We can remove thus tough and instruct the user to create it alongside a shortcut.

2023-06-19 06:24 UTC, kArmadi110 commented on main.py
> +
Of course.

2023-06-19 06:37 UTC, kArmadi110 commented on main.py
> +
else branch added

2023-06-19 06:38 UTC, maraid approved these changes

2023-06-19 06:39 UTC, merged